In [1]:
import datetime
import pandas as pd
import time
import requests
import os
import numpy as np
import xlsxwriter
from abc import ABCMeta, abstractmethod
from Queue import Queue
from collections import deque
import getpass
import pandas.io.formats.excel

In [2]:
# TODOs:

# PNL reporting/collecting relevant statistics for visualizations from our simulations

# Longer time horizons. Only weight according to n most recent time steps

# Benchmarks: 
## - Buy and hold market index (Dow Jones)
## - Constantly Rebalanced Portfolio (maintain equal weights of each asset at all times)

# Non-fractional shares

# Contexts

# Other trading strategies
## Fundamentals-based strategies (need to get more data for this)



### Simulation runner

In [24]:

class SimulationEnv(object):
    
    loggables = ['positions']
    
    def __init__(self, wealth, assets, 
                 path_to_data, start_date, end_date,
                 agent_type, expert_type, reinvest, max_assets=100):

        self.init_wealth = wealth
        self.wealth = wealth
        self.assets = assets
        self.agent_type = agent_type
        self.expert_type = expert_type
        self.path_to_data = path_to_data
        self.reinvest = reinvest
        self.max_assets = max_assets
        ## TODO: 
        ## - specify start and end date for simulation
        ## - collect statistics on simulation results
        self.start_date = start_date
        self.end_date = end_date
        
        return
    
    
    ## To be called before running a simulation - initialize experts, agents, and initial position, etc.

    def setup_params(self, agent_args={}, expert_args={}):
    
        stdevs = {}
        for f in os.listdir(self.path_to_data):
            df = pd.read_csv(self.path_to_data+f)
            df = df[df["date"] < self.start_date]
            df["return"] = (df["adj_close"] - df["adj_close"].shift(1))/df["adj_close"].shift(1)
            stdevs[f] = df["return"].std()
            self.assets = [f.split(".")[0].upper() for f in sorted(stdevs, key=stdevs.get, reverse=True)[:self.max_assets]]
        print self.assets
        self.experts = [self.expert_type(a, self.path_to_data, **expert_args) for a in self.assets]
        self.agent = self.agent_type(self.experts, **agent_args)
        self.positions = np.array([weight * self.wealth for weight in self.agent.weights])
        
        ## TODO: 
        # do various other stuff here like for select for high-volatility stocks or something
        # exception handling
        # Need to make sure data files are in sync
        
        return
        
    ## Run simulation
    def run(self, log=False, logpath=os.getcwd()):
        
        ## Start period counter and log
        self.period = 1
        self.finallog = []
        self.log = log
        self.logpath = logpath
        
        ## Warmup period: 
        ## i.e. for strategies involving moving average indicators, wait until we have enough data to calculate MA
        for expert in self.agent.experts:
            expert.warmup()
        
        ## Simulation: Go until data iterators reach the end
        while True:
            try:
                print "PERIOD {}".format(self.period)
                print "positions:"
                print np.array([weight * self.wealth for weight in self.agent.weights])
                print "weights:"
                print np.array([weight for weight in self.agent.weights])
                
                if self.period > 1:
                    print "rewards:"
                    print np.array([r for r in self.agent.rewards])
                    print "returns:"
                    print np.array([r for r in self.agent.returns])

                print "---------------------"
                ## Log this period
                if log:
                    self.logperiod()
                    
                ## Update experts with last period's rewards
                for i, expert in enumerate(self.agent.experts):
                    expert.update()
                    if self.reinvest:# below is to redistribute unallocated money
                        if expert.pick == False:
                            extra_money = self.positions[i]
                            self.positions[i] = 0
                            distribute = np.greater(self.positions, 0)
                            if not np.any(distribute): # this is to avoid divide by zero if nothing is invested
                                #print("all experts say not to buy")
                                self.positions = np.array([weight * self.wealth for weight in self.agent.weights])
                            else:
                                distribute_extra_money = distribute * (extra_money/ np.sum(distribute))
                                self.positions = np.add(self.positions, distribute_extra_money)
                            assert(abs(np.sum(self.positions)-self.wealth) <= 1)# make sure all money is accounted for
                      
                ## Update agent accordingly (i.e. for Hedge, update weights according to each expert's reward in the last period)
                self.agent.update()
                

                
                ## Update position with returns from last period
                self.positions = self.positions * (1 + self.agent.returns)
                self.wealth = np.sum(self.positions)
                
                ## Rebalance according to new, updated weights
                ## TODO: only allow non-fractional shares to be purchased (?)
                if np.sum(self.agent.weights) == 1:
                    self.positions = np.array([weight * self.wealth for weight in self.agent.weights])
                    
                print "new weights:"
                print np.array([weight for weight in self.agent.weights])
                print "---------------------"
                print "\n\n"
                
                
                ## Advance period
                self.period += 1
                
            except StopIteration:
                break
        
        ## Write the log file
        if log:
            self.savelog()

    def logperiod(self):
        row = [self.period] + [self.wealth]
        nrow = []
        for loggable in (self.loggables):
            if getattr(self,loggable) is None:
                nrow += [None] * len(self.experts)
            else:
                nrow += getattr(self,loggable).tolist()
        arow = []
        for loggable in (self.agent_type.loggables):
            if getattr(self.agent,loggable) is None:
                arow += [None] * len(self.experts)
            else:
                arow += getattr(self.agent,loggable).tolist()
        erow = []
        for loggable in (self.expert_type.loggables):
            if [getattr(e,loggable) for e in self.experts] is None:
                erow += [None] * len(self.experts)
            else:
                erow += [getattr(e,loggable) for e in self.experts]
        row += nrow + arow + erow
        self.finallog.append(row)
    
    def savelog(self):
        runtime = datetime.datetime.now()
        runuser = getpass.getuser()
        logname = runuser + "_" + runtime.strftime('%Y-%m-%d_%H-%M-%S')
        if not os.path.exists(os.path.join(self.logpath, logname)):
            os.makedirs(os.path.join(self.logpath, logname))
        col = ['period', 'wealth'] + \
            [x+'.'+y for x in self.loggables for y in self.assets] + \
            [x+'.'+y for x in self.agent_type.loggables for y in self.assets] + \
            [x+'.'+y for x in self.expert_type.loggables for y in self.assets]
        df = pd.DataFrame(self.finallog, columns=col)
        df.set_index('period', inplace=True)
        
        
        writer = pd.ExcelWriter(os.path.join(self.logpath, logname, logname+'.xlsx'), engine='xlsxwriter')
        pd.io.formats.excel.header_style = None
        df.to_excel(writer,'run_log')
        
        workbook  = writer.book
        worksheet = writer.sheets['run_log']
        
        header_format = workbook.add_format({'bold': True,'text_wrap': True})
        worksheet.set_row(0, None, header_format)
        writer.save()



### Base classes

Base classes for agents and experts to be implemented by us

In [25]:

class Agent(object):
    __metaclass__ =ABCMeta
    
    @abstractmethod
    def __init__(self):
        pass
    
    @abstractmethod
    def update(self):
        pass
    
    @abstractmethod
    def act(self):
        pass
    
class Expert(object):
    __metaclass__=ABCMeta
    
    @abstractmethod
    def __init__(self, reward_data):
        pass
    
    @abstractmethod
    def update(self):
        pass
    
class Context(object):
    __metaclass__=ABCMeta
    
    @abstractmethod
    def __init__(self, context_data):
        pass
    
    @abstractmethod
    def observe(self):
        pass

### Agents

Implementations of different online portfolio selection algorithms
* Exponential Gradient
* Exponential Gradient (recent history only)

In [26]:
## EG. (http://www.cis.upenn.edu/~mkearns/finread/helmbold98line.pdf)
class EG(Agent):
    
    loggables = ['returns','rewards','weights']
    
    ## Initialize with a set of experts
    def __init__(self, experts, eta):
        self.eta = eta
        self.experts = experts
        self.weights = np.ones(len(self.experts))/len(self.experts)
        self.rewards = None
        self.returns = None
        return
    
    ## Update the agent's rewards and its weights for each expert
    def update(self):
        self.rewards = np.asarray([e.reward for e in self.experts])
        self.returns = np.asarray([e.returns for e in self.experts])
        multipliers = np.exp(self.eta * self.rewards/np.sum(self.weights * self.rewards))
        self.weights = (self.weights * multipliers)/ np.sum(self.weights * multipliers)
        self.weights = np.nan_to_num(self.weights)

        return
    
    def act(self):
        return self.weights


class EGRecent(Agent):
    
    loggables = ['returns','rewards','weights']
    
    ## Initialize with a set of experts
    def __init__(self, experts, eta, n):
        self.eta = eta
        self.experts = experts
        #self.weights = Queue(maxsize=n)
        self.weights = np.ones(len(self.experts))/len(self.experts)
        self.rewards = deque(maxlen=n)
        self.returns = None
        self.t = 0
        self.n = n
        #self.rewards = None
        #self.returns = None
        return
    
    ## Update the agent's rewards and its weights for each expert
    def update(self):
           
        self.rewards.append(np.asarray([e.reward for e in self.experts]))
        self.returns = np.asarray([e.returns for e in self.experts])
        
        self.weights = np.ones(len(self.experts))/len(self.experts)
        #print self.t
        #print len(self.rewards)
        for rewards in self.rewards:
            rewards = np.asarray(rewards)
            multipliers = np.exp(self.eta * rewards/np.sum(self.weights * rewards))
            self.weights = (self.weights * multipliers)/ np.sum(self.weights * multipliers)
            self.weights = np.nan_to_num(self.weights)
        self.t += 1
        #print self.t
        
        return
    
    def act(self):
        return self.weights
    
      
        

More agents to serve as naive/benchmark portfolio allocation algorithms:
* Equal-weighted buy and hold
* Market-weighted buy and hold
* Constantly rebalanced portfolio


In [27]:
## Some other examples of agents to use as benchmarks 

class NaiveBuyHold(Agent):
    
    loggables = ['rewards','weights']
    
    def __init__(self, experts):
        self.experts = experts
        self.weights = np.ones(len(self.experts))/len(self.experts)
        self.rewards = None
        return
    
    def update(self):
        self.rewards = np.asarray([e.reward for e in self.experts])
        self.returns = self.rewards
        return
    
    def act(self):
        return self.weights
    
## TODO
class WeightedBuyHold(Agent):
    
    def __init__(self):
        return
    
    def update(self):
        return
    
    def act(self):
        return
    

## to be used with "Dummy" Expert for each stock
class ConstantRebalancer(Agent):
    
    def __init__(self, experts):
        self.experts = experts
        self.weights = np.ones(len(self.experts))/len(self.experts)
        self.rewards = None
        return
    
    def update(self):
        self.rewards = np.asarray([e.reward for e in self.experts])
        self.returns = self.rewards
        multipliers = np.asarray([e.reward + 1 for e in self.experts])
        self.weights = np.multiply(self.weights, np.reciprocal(multipliers))
        self.weights = np.divide(self.weights, np.sum(self.weights))
        assert((np.sum(self.weights) - 1) <= 0.00001)
        return
    
    def act(self):
        return self.weights

### Experts

* Dummy
* Mean Reversion
* Momentum

In [28]:

## Dummy expert that always pick the same asset
class Dummy(Expert):
    
    loggables = ['reward']
    
    ## Expert has a reward associated with its pick
    def __init__(self, name, path_to_data):
        self.reward = 0.
        self.pick = True ## Might not be necessary
        self.data = pd.read_csv(path_to_data + name + ".csv", iterator=True, chunksize=1)
        self.last_price = float(self.data.get_chunk(1)["adj_close"])
        return
    
    ## Expert updates its reward 
    def update(self):
        current_price = float(self.data.get_chunk(1)["adj_close"])
        self.reward = current_price/self.last_price
        self.returns = self.reward - 1.
        self.last_price = current_price
        return
    
    def warmup(self):
        pass
    

class MeanReversion(Expert):
    
    loggables = ['avg','std']
    
    def __init__(self, name, path_to_data, window_size, threshold):
        self.reward = 0.
        self.pick = False
        self.data = pd.read_csv(path_to_data + name + ".csv", iterator=True, chunksize=1)
        self.last_price = float(self.data.get_chunk(1)["adj_close"])
        self.window_size = window_size
        self.avg = 0.0
        self.std = 0.0
        self.threshold = threshold
        self.last_n_prices = Queue(maxsize=10)
        self.returns = 0.
        return
    
    def warmup(self):
        n = 1
        while n <= self.window_size:
            self.last_n_prices.put(self.last_price)
            self.last_price = float(self.data.get_chunk(1)["adj_close"])
            n += 1
        return
        
    def update(self):
        _ = self.last_n_prices.get()
            
        self.last_n_prices.put(self.last_price)
        self.avg = np.mean(list(self.last_n_prices.queue))
        self.std = np.std(list(self.last_n_prices.queue))
        
        current_price = float(self.data.get_chunk(1)["adj_close"])

        ## If self.pick is True, we bought the stock and our reward is whatever the return was in the last period
        if self.pick:
            self.reward = current_price/self.last_price
            self.returns = self.reward - 1.
        else:
            self.reward = -current_price/self.last_price
            self.returns = 0
        self.last_price = current_price

        if self.last_price <= self.avg - self.threshold * self.std:
            self.pick = True
        else:
            self.pick = False

        return
    
    
class Momentum(Expert):
    
    loggables = ['avg','std']
    
    def __init__(self, name, path_to_data, window_size, threshold):
        self.reward = 0.
        self.pick = False
        self.data = pd.read_csv(path_to_data + name + ".csv", iterator=True, chunksize=1)
        self.last_price = float(self.data.get_chunk(1)["adj_close"])
        self.window_size = window_size
        self.avg = 0.0
        self.std = 0.0
        self.threshold = threshold
        self.last_n_prices = Queue(maxsize=10)
        self.returns = 0.
        return
    
    def warmup(self):
        n = 1
        while n <= self.window_size:
            self.last_n_prices.put(self.last_price)
            self.last_price = float(self.data.get_chunk(1)["adj_close"])
            n += 1
        return
        
    def update(self):
        _ = self.last_n_prices.get()
            
        self.last_n_prices.put(self.last_price)
        self.avg = np.mean(list(self.last_n_prices.queue))
        self.std = np.std(list(self.last_n_prices.queue))
        
        current_price = float(self.data.get_chunk(1)["adj_close"])

        ## If self.pick is True, we bought the stock and our reward is whatever the return was in the last period
        if self.pick:
            self.reward = current_price/self.last_price
            self.returns = self.reward - 1.
        else:
            self.reward = -current_price/self.last_price
            self.returns = 0
        self.last_price = current_price

        if self.last_price >= self.avg - self.threshold * self.std:
            self.pick = True
        else:
            self.pick = False

        return
  

### Contexts

In [29]:
  
class VolContext(Context):
    
    def __init__(self, data_file, threshold):
        self.data = pd.read_csv(data_file, iterator=True, chunksize=1)
        self.threshold = threshold
        self.contexts = ["HighVol", "LowVol"]
        return
    
    # Returns a string giving the name of the context
    def observe(self):
        if float(self.data.get_chunk(1)["adj_close"]) > self.threshold:
            return self.contexts[0]
        else:
            return self.contexts[1]

In [30]:
stocks = ['AAPL', 'AXP', 'BA', 'CAT', 'CSCO', 'CVX', 'DD', 'DIS', 'GE',
 'GS', 'HD', 'IBM', 'INTC', 'JNJ', 'JPM', 'KO', 'MCD', 'MMM', 
'MRK', 'MSFT', 'NKE', 'PFE', 'PG', 'TRV', 'UNH', 'UTX', 'VZ', 'WMT', 'XOM']
stocks = [stock.lower() for stock in stocks]

In [31]:
initial_wealth = 100000

In [33]:
## Run simulation where constantly rebalance investments
start = time.time()
s = SimulationEnv(initial_wealth, stocks, "data/djia_20150101_20171101/", "2016-01-01", "2017-11-01", EG, Dummy, True, max_assets=5)
s.setup_params(agent_args={"eta": 0.01})
s.run()

years = 2. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1
end = time.time()

print("Initial wealth: ${}".format(initial_wealth))
print("Final wealth: ${}".format(s.wealth))
print("Annualized return: {}".format(ar))
print("Time: {}s".format(int(end-start)))

['MSFT', 'CVX', 'DD', 'AAPL', 'CAT']
PERIOD 1
positions:
[ 20000.  20000.  20000.  20000.  20000.]
weights:
[ 0.2  0.2  0.2  0.2  0.2]
---------------------
new weights:
[ 0.20004573  0.19998239  0.20000918  0.20000676  0.19995594]
---------------------



PERIOD 2
positions:
[ 19375.50921855  19369.37503682  19371.9697586   19371.73496985
  19366.81249853]
weights:
[ 0.20004573  0.19998239  0.20000918  0.20000676  0.19995594]
rewards:
[ 0.99069718  0.96002842  0.97300231  0.97182841  0.94721376]
returns:
[-0.00930282 -0.03997158 -0.02699769 -0.02817159 -0.05278624]
---------------------
new weights:
[ 0.20002966  0.19999473  0.19999915  0.20002022  0.19995625]
---------------------



PERIOD 3
positions:
[ 19245.36022854  19241.99979339  19242.42528522  19244.45205883
  19238.29755053]
weights:
[ 0.20002966  0.19999473  0.19999915  0.20002022  0.19995625]
rewards:
[ 0.98542903  0.99953738  0.98842722  1.00009412  0.99356544]
returns:
[ -1.45709660e-02  -4.62620281e-04  -1.15727830e-02

---------------------
new weights:
[ 0.19984163  0.19997558  0.20009354  0.20022955  0.19985971]
---------------------



PERIOD 24
positions:
[ 19690.02259554  19703.22070265  19714.84270173  19728.24333527
  19691.80388188]
weights:
[ 0.19984163  0.19997558  0.20009354  0.20022955  0.19985971]
rewards:
[ 1.01457935  1.00886018  1.03064822  1.0071094   1.01976815]
returns:
[ 0.01457935  0.00886018  0.03064822  0.0071094   0.01976815]
---------------------
new weights:
[ 0.19984359  0.19998493  0.20010003  0.20021651  0.19985493]
---------------------



PERIOD 25
positions:
[ 19652.58317891  19666.48263296  19677.80128173  19689.25587235
  19653.69835104]
weights:
[ 0.19984359  0.19998493  0.20010003  0.20021651  0.19985493]
rewards:
[ 0.99905771  1.00274449  1.00131579  0.99157912  0.99569223]
returns:
[-0.00094229  0.00274449  0.00131579 -0.00842088 -0.00430777]
---------------------
new weights:
[ 0.19983111  0.19998967  0.20007994  0.20021959  0.19987969]
---------------------





new weights:
[ 0.1998577   0.19987794  0.20015585  0.20033169  0.19977682]
---------------------



PERIOD 45
positions:
[ 19862.85609287  19864.86741062  19892.48762193  19909.96371447
  19854.81742939]
weights:
[ 0.1998577   0.19987794  0.20015585  0.20033169  0.19977682]
rewards:
[ 1.01156752  1.00386287  1.00550294  1.0042654   1.00936797]
returns:
[ 0.01156752  0.00386287  0.00550294  0.0042654   0.00936797]
---------------------
new weights:
[ 0.19984263  0.19988133  0.20018467  0.20031345  0.19977792]
---------------------



PERIOD 46
positions:
[ 19629.30172902  19633.10334664  19662.89808198  19675.54699641
  19622.94577532]
weights:
[ 0.19984263  0.19988133  0.20018467  0.20031345  0.19977792]
rewards:
[ 0.98086348  0.98999519  1.0025455   0.97931414  0.98886276]
returns:
[-0.01913652 -0.01000481  0.0025455  -0.02068586 -0.01113724]
---------------------
new weights:
[ 0.19984399  0.19989734  0.20020166  0.20028061  0.1997764 ]
---------------------



PERIOD 47
positions:
[

new weights:
[ 0.19983628  0.19995675  0.20001122  0.20035742  0.19983833]
---------------------



PERIOD 69
positions:
[ 19583.89670067  19595.70241945  19601.04095944  19634.96781074
  19584.0968472 ]
weights:
[ 0.19983628  0.19995675  0.20001122  0.20035742  0.19983833]
rewards:
[ 1.00095877  0.996165    0.99626194  0.99803304  0.99443099]
returns:
[ 0.00095877 -0.003835   -0.00373806 -0.00196696 -0.00556901]
---------------------
new weights:
[ 0.19981928  0.19998865  0.20000773  0.20033698  0.19984735]
---------------------



PERIOD 70
positions:
[ 19698.24436458  19714.94089973  19716.8221329   19749.27956889
  19701.01193427]
weights:
[ 0.19981928  0.19998865  0.20000773  0.20033698  0.19984735]
rewards:
[ 0.9973659   1.02197183  1.00416898  0.99566417  1.01046993]
returns:
[-0.0026341   0.02197183  0.00416898 -0.00433583  0.01046993]
---------------------
new weights:
[ 0.19982564  0.19999482  0.19998099  0.20032211  0.19987644]
---------------------



PERIOD 71
positions:
[

new weights:
[ 0.20002917  0.19990201  0.19987723  0.20029261  0.19989897]
---------------------



PERIOD 93
positions:
[ 20665.80094684  20652.6633413   20650.10302179  20693.01801709
  20652.34965203]
weights:
[ 0.20002917  0.19990201  0.19987723  0.20029261  0.19989897]
rewards:
[ 0.99127668  1.00599355  1.00832496  0.99860411  0.99650665]
returns:
[-0.00872332  0.00599355  0.00832496 -0.00139589 -0.00349335]
---------------------
new weights:
[ 0.20002251  0.19988158  0.19987498  0.20031994  0.19990097]
---------------------



PERIOD 94
positions:
[ 20611.76532196  20597.24270694  20596.56276895  20642.41445504
  20599.24096898]
weights:
[ 0.20002251  0.19988158  0.19987498  0.20031994  0.19990097]
rewards:
[ 0.99409877  0.98722577  0.99629893  1.01102741  0.99841683]
returns:
[-0.00590123 -0.01277423 -0.00370107  0.01102741 -0.00158317]
---------------------
new weights:
[ 0.20002255  0.199856    0.19991611  0.20032315  0.19988219]
---------------------



PERIOD 95
positions:
[

rewards:
[ 1.01631499  1.00491179  1.00949777  1.00455617  1.00217765]
returns:
[ 0.01631499  0.00491179  0.00949777  0.00455617  0.00217765]
---------------------
new weights:
[ 0.20001117  0.19979904  0.19992812  0.2003208   0.19994086]
---------------------



PERIOD 117
positions:
[ 20039.15794369  20017.90494775  20030.83729093  20070.17980433
  20032.11401196]
weights:
[ 0.20001117  0.19979904  0.19992812  0.2003208   0.19994086]
rewards:
[ 0.98672945  0.99221945  0.9955809   0.98999062  1.00091491]
returns:
[-0.01327055 -0.00778055 -0.0044191  -0.01000938  0.00091491]
---------------------
new weights:
[ 0.20000494  0.1998036   0.19992056  0.20032483  0.19994607]
---------------------



PERIOD 118
positions:
[ 20157.80390472  20137.5107896   20149.29934711  20190.04463609
  20151.87001404]
weights:
[ 0.20000494  0.1998036   0.19992056  0.20032483  0.19994607]
rewards:
[ 1.00281996  1.00824369  1.00214777  1.00797788  1.00856947]
returns:
[ 0.00281996  0.00824369  0.00214777  0.

new weights:
[ 0.20010141  0.19979052  0.19980492  0.20041488  0.19988828]
---------------------



PERIOD 139
positions:
[ 18940.91920694  18911.49142801  18912.85462279  18970.59107586
  18920.74537395]
weights:
[ 0.20010141  0.19979052  0.19980492  0.20041488  0.19988828]
rewards:
[ 0.96319797  0.99584665  0.99358974  0.95770554  0.97008027]
returns:
[-0.03680203 -0.00415335 -0.00641026 -0.04229446 -0.02991973]
---------------------
new weights:
[ 0.20014167  0.19979324  0.19980556  0.20042895  0.19983058]
---------------------



PERIOD 140
positions:
[ 18803.5595079   18770.82494064  18771.98222238  18830.55051461
  18774.33220495]
weights:
[ 0.20014167  0.19979324  0.19980556  0.20042895  0.19983058]
rewards:
[ 1.01251647  0.9939044   0.99286927  0.99952084  0.96389168]
returns:
[ 0.01251647 -0.0060956  -0.00713073 -0.00047916 -0.03610832]
---------------------
new weights:
[ 0.20016283  0.19977082  0.1997808   0.20044693  0.19983862]
---------------------



PERIOD 141
positions

PERIOD 160
positions:
[ 17533.08294515  17477.63533612  17486.22146378  17541.11503889
  17505.21401474]
weights:
[ 0.20027905  0.19964568  0.19974376  0.2003708   0.19996071]
rewards:
[ 0.97961811  0.97935978  0.98607714  0.97948005  0.98708177]
returns:
[-0.02038189 -0.02064022 -0.01392286 -0.02051995 -0.01291823]
---------------------
new weights:
[ 0.20023933  0.19963264  0.19980564  0.20032182  0.20000057]
---------------------



PERIOD 161
positions:
[ 16871.06077671  16819.94490351  16834.52067884  16878.01100787
  16850.94395258]
weights:
[ 0.20023933  0.19963264  0.19980564  0.20032182  0.20000057]
rewards:
[ 0.94327639  0.95608279  0.99217707  0.93883711  0.98154692]
returns:
[-0.05672361 -0.04391721 -0.00782293 -0.06116289 -0.01845308]
---------------------
new weights:
[ 0.20024422  0.1996049   0.19979691  0.20034188  0.20001209]
---------------------



PERIOD 162
positions:
[ 16287.22231028  16235.22242022  16250.84017498  16295.16602784
  16268.34197421]
weights:
[ 0.20

positions:
[ 16740.34181601  16687.52580126  16687.35101978  16757.35178878
  16706.29847908]
weights:
[ 0.20029395  0.19966202  0.19965993  0.20049747  0.19988663]
rewards:
[ 0.99931663  0.98537217  0.98641137  1.00811287  0.97935268]
returns:
[-0.00068337 -0.01462783 -0.01358863  0.00811287 -0.02064732]
---------------------
new weights:
[ 0.20031323  0.19969978  0.19968235  0.20052696  0.19977768]
---------------------



PERIOD 184
positions:
[ 16600.09381957  16549.2566468   16547.81285745  16617.80549691
  16555.71285055]
weights:
[ 0.20031323  0.19969978  0.19968235  0.20052696  0.19977768]
rewards:
[ 1.00091178  1.01011561  1.0025047   1.00594822  0.93732194]
returns:
[ 0.00091178  0.01011561  0.0025047   0.00594822 -0.06267806]
---------------------
new weights:
[ 0.20031178  0.19971798  0.19970114  0.20051909  0.19975002]
---------------------



PERIOD 185
positions:
[ 16623.33269047  16574.05473718  16572.6571146   16640.53658203
  16576.71346487]
weights:
[ 0.20031178  0.1

[ 0.20040056  0.19975482  0.1998493   0.20031058  0.19968474]
rewards:
[ 1.10077035  0.99585243  1.01824633  1.03099567  1.01227427]
returns:
[ 0.10077035 -0.00414757  0.01824633  0.03099567  0.01227427]
---------------------
new weights:
[ 0.20046711  0.1997142   0.19986648  0.20026009  0.19969212]
---------------------



PERIOD 206
positions:
[ 19085.05102054  19013.37205778  19027.86910303  19065.34210746
  19011.26950126]
weights:
[ 0.20046711  0.1997142   0.19986648  0.20026009  0.19969212]
rewards:
[ 1.02610176  0.97292854  1.0016592   0.96808868  0.99679443]
returns:
[ 0.02610176 -0.02707146  0.0016592  -0.03191132 -0.00320557]
---------------------
new weights:
[ 0.20045306  0.19969674  0.19992899  0.20025407  0.19966715]
---------------------



PERIOD 207
positions:
[ 19020.01429291  18948.25048944  18970.28743371  19001.13324447
  18945.44301839]
weights:
[ 0.20045306  0.19969674  0.19992899  0.20025407  0.19966715]
rewards:
[ 0.98967742  0.98794638  1.02782839  0.99366759 

new weights:
[ 0.20040194  0.19970882  0.2000241   0.20024687  0.19961827]
---------------------



PERIOD 229
positions:
[ 19734.53616742  19666.28063094  19697.32820883  19719.26577361
  19657.36425301]
weights:
[ 0.20040194  0.19970882  0.2000241   0.20024687  0.19961827]
rewards:
[ 1.00447011  0.99449763  0.99747249  0.99813607  0.99622325]
returns:
[ 0.00447011 -0.00550237 -0.00252751 -0.00186393 -0.00377675]
---------------------
new weights:
[ 0.20039905  0.19971132  0.20001316  0.20023678  0.1996397 ]
---------------------



PERIOD 230
positions:
[ 19916.72181159  19848.37195284  19878.37036959  19900.59492756
  19841.25361107]
weights:
[ 0.20039905  0.19971132  0.20001316  0.20023678  0.1996397 ]
rewards:
[ 1.00778787  1.01051234  1.00372634  1.00415924  1.02007863]
returns:
[ 0.00778787  0.01051234  0.00372634  0.00415924  0.02007863]
---------------------
new weights:
[ 0.2004292   0.19973478  0.20000949  0.20021865  0.19960789]
---------------------



PERIOD 231
positions

new weights:
[ 0.20051348  0.19975552  0.20007419  0.20007638  0.19958042]
---------------------



PERIOD 252
positions:
[ 19240.02492873  19167.29525935  19197.87314823  19198.08357839
  19150.49411927]
weights:
[ 0.20051348  0.19975552  0.20007419  0.20007638  0.19958042]
rewards:
[ 0.98526017  0.998557    0.98915788  0.98080507  0.98937254]
returns:
[-0.01473983 -0.001443   -0.01084212 -0.01919493 -0.01062746]
---------------------
new weights:
[ 0.20051961  0.19976146  0.19999753  0.20010914  0.19961226]
---------------------



PERIOD 253
positions:
[ 18946.8522892   18875.21510253  18897.52175218  18908.06746482
  18861.11769929]
weights:
[ 0.20051961  0.19976146  0.19999753  0.20010914  0.19961226]
rewards:
[ 0.98774333  0.98766118  0.946997    1.00085503  1.00044144]
returns:
[-0.01225667 -0.01233882 -0.053003    0.00085503  0.00044144]
---------------------
new weights:
[ 0.20053004  0.19977983  0.20003721  0.20006025  0.19959268]
---------------------



PERIOD 254
positions


PERIOD 274
positions:
[ 17822.58289945  17755.38487923  17772.70272616  17779.0261328
  17740.0662411 ]
weights:
[ 0.20054721  0.19979107  0.19998594  0.20005709  0.1996187 ]
rewards:
[ 0.98415094  1.04160512  1.04592382  1.01979255  1.04285479]
returns:
[-0.01584906  0.04160512  0.04592382  0.01979255  0.04285479]
---------------------
new weights:
[ 0.20051925  0.19977324  0.19997556  0.20005108  0.19968087]
---------------------



PERIOD 275
positions:
[ 18016.63916999  17949.61072571  17967.78928749  17974.57419567
  17941.3113232 ]
weights:
[ 0.20051925  0.19977324  0.19997556  0.20005108  0.19968087]
rewards:
[ 0.99693252  1.00200898  1.00578625  1.0079917   1.0425162 ]
returns:
[-0.00306748  0.00200898  0.00578625  0.0079917   0.0425162 ]
---------------------
new weights:
[ 0.20048207  0.19976234  0.20000326  0.20003165  0.19972068]
---------------------



PERIOD 276
positions:
[ 17707.20931507  17643.64021777  17664.91866479  17667.42641703
  17639.96010358]
weights:
[ 0.20

new weights:
[ 0.20043122  0.19984676  0.19999608  0.20000688  0.19971906]
---------------------



PERIOD 298
positions:
[ 19284.22784259  19227.99528855  19242.36178649  19243.40075107
  19215.70893002]
weights:
[ 0.20043122  0.19984676  0.19999608  0.20000688  0.19971906]
rewards:
[ 1.02303969  1.04597701  0.99874075  1.00089082  1.00195176]
returns:
[ 0.02303969  0.04597701 -0.00125925  0.00089082  0.00195176]
---------------------
new weights:
[ 0.20041311  0.19988302  0.19996719  0.20001988  0.1997168 ]
---------------------



PERIOD 299
positions:
[ 19167.3760263   19116.67930543  19124.72850441  19129.76847953
  19100.78155042]
weights:
[ 0.20041311  0.19988302  0.19996719  0.20001988  0.1997168 ]
rewards:
[ 0.98504921  1.01206637  0.97966903  1.00049446  0.99290385]
returns:
[-0.01495079  0.01206637 -0.02033097  0.00049446 -0.00709615]
---------------------
new weights:
[ 0.20041853  0.1998633   0.19998689  0.20000794  0.19972334]
---------------------



PERIOD 300
positions

new weights:
[ 0.20042078  0.19983369  0.19992393  0.20009251  0.19972909]
---------------------



PERIOD 320
positions:
[ 19932.2419714   19873.85474428  19882.82869024  19899.5941717
  19863.45150187]
weights:
[ 0.20042078  0.19983369  0.19992393  0.20009251  0.19972909]
rewards:
[ 0.99797868  0.98868473  1.00031646  1.00331309  1.00376597]
returns:
[-0.00202132 -0.01131527  0.00031646  0.00331309  0.00376597]
---------------------
new weights:
[ 0.20040156  0.19984909  0.19992636  0.20008664  0.19973635]
---------------------



PERIOD 321
positions:
[ 20249.31406521  20193.49067473  20201.29798878  20217.49299934
  20182.09824728]
weights:
[ 0.20040156  0.19984909  0.19992636  0.20008664  0.19973635]
rewards:
[ 1.00626036  1.02383452  1.01724138  1.01302513  1.01969717]
returns:
[ 0.00626036  0.02383452  0.01724138  0.01302513  0.01969717]
---------------------
new weights:
[ 0.20039699  0.19982113  0.19991157  0.20008538  0.19978493]
---------------------



PERIOD 322
positions:




PERIOD 343
positions:
[ 19293.81432913  19260.61370947  19260.15497542  19237.46673478
  19231.33946201]
weights:
[ 0.2003857   0.20004088  0.20003611  0.19980047  0.19973684]
rewards:
[ 1.00901077  1.00968954  0.99953351  0.97654308  0.9899213 ]
returns:
[ 0.00901077  0.00968954 -0.00046649 -0.02345692 -0.0100787 ]
---------------------
new weights:
[ 0.2003947   0.20003939  0.20001883  0.19983038  0.1997167 ]
---------------------



PERIOD 344
positions:
[ 19046.23637197  19012.46692845  19010.51212418  18992.60105732
  18981.79695653]
weights:
[ 0.2003947   0.20003939  0.20001883  0.19983038  0.1997167 ]
rewards:
[ 0.99165211  0.98648649  0.97868699  1.00199247  0.97726639]
returns:
[-0.00834789 -0.01351351 -0.02131301  0.00199247 -0.02273361]
---------------------
new weights:
[ 0.20038468  0.20003078  0.20002461  0.19986435  0.19969557]
---------------------



PERIOD 345
positions:
[ 19421.99886578  19387.69689311  19387.09977218  19371.56682121
  19355.20779786]
weights:
[ 0

[-0.00280955 -0.00641785 -0.00136674 -0.0032834   0.00280524]
---------------------
new weights:
[ 0.20029716  0.19998172  0.20005853  0.1998949   0.19976769]
---------------------



PERIOD 367
positions:
[ 19871.60345251  19840.30814164  19847.92918282  19831.69498342
  19819.07488812]
weights:
[ 0.20029716  0.19998172  0.20005853  0.1998949   0.19976769]
rewards:
[ 1.01408734  1.00437245  1.0176399   1.00422071  0.99893433]
returns:
[ 0.01408734  0.00437245  0.0176399   0.00422071 -0.00106567]
---------------------
new weights:
[ 0.20028854  0.19999334  0.20007253  0.1998511   0.19979448]
---------------------



PERIOD 368
positions:
[ 19853.59064956  19824.32894609  19832.17800086  19810.22887001
  19804.61679736]
weights:
[ 0.20028854  0.19999334  0.20007253  0.1998511   0.19979448]
rewards:
[ 0.99484025  1.00494707  1.00612672  0.97724244  1.012535  ]
returns:
[-0.00515975  0.00494707  0.00612672 -0.02275756  0.012535  ]
---------------------
new weights:
[ 0.20027958  0.2000071

[ 0.05311735 -0.00424368  0.00281523  0.00090117 -0.00062704]
---------------------
new weights:
[ 0.20040149  0.19996436  0.19998578  0.19983249  0.19981589]
---------------------



PERIOD 391
positions:
[ 20922.23903756  20876.60171842  20878.83796044  20862.83443885
  20861.10115249]
weights:
[ 0.20040149  0.19996436  0.19998578  0.19983249  0.19981589]
rewards:
[ 0.99803255  0.99810588  1.00251182  0.99469788  1.00401556]
returns:
[-0.00196745 -0.00189412  0.00251182 -0.00530212  0.00401556]
---------------------
new weights:
[ 0.20042536  0.19996574  0.19999911  0.19981332  0.19979646]
---------------------



PERIOD 392
positions:
[ 20963.78366941  20915.70960079  20919.19995939  20899.76649173
  20898.00304649]
weights:
[ 0.20042536  0.19996574  0.19999911  0.19981332  0.19979646]
rewards:
[ 1.01379928  1.00256191  1.00854827  0.99225586  0.99212598]
returns:
[ 0.01379928  0.00256191  0.00854827 -0.00774414 -0.00787402]
---------------------
new weights:
[ 0.20044607  0.1999313

new weights:
[ 0.20041146  0.19984692  0.19999164  0.19993385  0.19981613]
---------------------



PERIOD 415
positions:
[ 21771.07613331  21709.74873151  21725.46957352  21719.19149586
  21706.4041455 ]
weights:
[ 0.20041146  0.19984692  0.19999164  0.19993385  0.19981613]
rewards:
[ 1.00103645  1.00511408  0.99900625  0.9924667   0.98976312]
returns:
[ 0.00103645  0.00511408 -0.00099375 -0.0075333  -0.01023688]
---------------------
new weights:
[ 0.20042272  0.19984447  0.19999156  0.19992894  0.19981229]
---------------------



PERIOD 416
positions:
[ 21732.86735571  21670.16485384  21686.11467022  21679.3243874
  21666.6755233 ]
weights:
[ 0.20042272  0.19984447  0.19999156  0.19992894  0.19981229]
rewards:
[ 1.00379638  0.99696673  0.99815262  0.99574192  0.9962718 ]
returns:
[ 0.00379638 -0.00303327 -0.00184738 -0.00425808 -0.0037282 ]
---------------------
new weights:
[ 0.20042771  0.19984305  0.1999845   0.19992699  0.19981774]
---------------------



PERIOD 417
positions:

[ 1.01845343  1.0020247   1.01112447  1.00186038  1.00619157]
returns:
[ 0.01845343  0.0020247   0.01112447  0.00186038  0.00619157]
---------------------
new weights:
[ 0.20039379  0.19982639  0.19987933  0.20002304  0.19987745]
---------------------



PERIOD 439
positions:
[ 22001.07714009  21938.78339524  21944.59496106  21960.37262526
  21944.38897466]
weights:
[ 0.20039379  0.19982639  0.19987933  0.20002304  0.19987745]
rewards:
[ 1.0013805   1.03202667  0.99895926  1.00760456  1.04476351]
returns:
[ 0.0013805   0.03202667 -0.00104074  0.00760456  0.04476351]
---------------------
new weights:
[ 0.20038683  0.19982397  0.19986968  0.20000667  0.19991284]
---------------------



PERIOD 440
positions:
[ 21837.24606049  21775.90797009  21780.88873158  21795.81769651
  21785.5929067 ]
weights:
[ 0.20038683  0.19982397  0.19986968  0.20000667  0.19991284]
rewards:
[ 0.98914355  0.99138522  0.9877958   0.98446687  1.01016284]
returns:
[-0.01085645 -0.00861478 -0.0122042  -0.01553313 

  22174.03990713]
weights:
[ 0.20043865  0.19985738  0.19990652  0.19999585  0.1998016 ]
rewards:
[ 1.00083514  1.00895781  0.99049676  0.99841716  0.99499285]
returns:
[ 0.00083514  0.00895781 -0.00950324 -0.00158284 -0.00500715]
---------------------
new weights:
[ 0.20044398  0.19989988  0.19990564  0.19996891  0.19978159]
---------------------



PERIOD 463
positions:
[ 22146.62037154  22086.50447625  22087.14095651  22094.13155104
  22073.43433358]
weights:
[ 0.20044398  0.19989988  0.19990564  0.19996891  0.19978159]
rewards:
[ 0.99799733  1.01651551  0.99491205  0.98194469  0.98538222]
returns:
[-0.00200267  0.01651551 -0.00508795 -0.01805531 -0.01461778]
---------------------
new weights:
[ 0.20044377  0.19989153  0.19991553  0.19998296  0.1997662 ]
---------------------



PERIOD 464
positions:
[ 22009.70602196  21949.06751372  21951.70265737  21959.10680044
  21935.3054556 ]
weights:
[ 0.20044377  0.19989153  0.19991553  0.19998296  0.1997662 ]
rewards:
[ 0.99381271  0.989763

new weights:
[ 0.20032034  0.19992551  0.19994492  0.19982649  0.19998274]
---------------------



PERIOD 484
positions:
[ 23489.10873353  23442.81162839  23445.08842746  23431.20187979
  23449.52290936]
weights:
[ 0.20032034  0.19992551  0.19994492  0.19982649  0.19998274]
rewards:
[ 0.98240956  1.01550735  1.00013585  0.99068042  1.00711595]
returns:
[-0.01759044  0.01550735  0.00013585 -0.00931958  0.00711595]
---------------------
new weights:
[ 0.20032849  0.19992681  0.19993801  0.19984044  0.19996625]
---------------------



PERIOD 485
positions:
[ 23413.77971344  23366.8330062   23368.14216462  23356.73809228
  23371.44272875]
weights:
[ 0.20032849  0.19992681  0.19993801  0.19984044  0.19996625]
rewards:
[ 1.00084459  0.9974402   0.9933442   1.00374463  0.98857024]
returns:
[ 0.00084459 -0.0025598  -0.0066558   0.00374463 -0.01142976]
---------------------
new weights:
[ 0.20036092  0.19993087  0.19993109  0.19982572  0.19995139]
---------------------



PERIOD 486
positions

[ 1.          0.99567136  0.99514629  1.00508533  0.9939083 ]
returns:
[ 0.         -0.00432864 -0.00485371  0.00508533 -0.0060917 ]
---------------------
new weights:
[ 0.20038889  0.19993585  0.19988706  0.19992351  0.19986469]
---------------------



PERIOD 508
positions:
[ 24113.43062063  24058.91403458  24053.04380098  24057.43008304
  24050.35141201]
weights:
[ 0.20038889  0.19993585  0.19988706  0.19992351  0.19986469]
rewards:
[ 1.00866774  0.99599352  0.99417423  1.01114827  1.00043011]
returns:
[ 0.00866774 -0.00400648 -0.00582577  0.01114827  0.00043011]
---------------------
new weights:
[ 0.20038458  0.19992078  0.1998984   0.19994391  0.19985234]
---------------------



PERIOD 509
positions:
[ 24088.05388203  24032.30131776  24029.61065619  24035.08161798
  24024.07463001]
weights:
[ 0.20038458  0.19992078  0.1998984   0.19994391  0.19985234]
rewards:
[ 0.99681731  0.99144129  1.00463342  1.00915953  0.9927988 ]
returns:
[-0.00318269 -0.00855871  0.00463342  0.00915953 

returns:
[ 0.01136722  0.00609428  0.00539758  0.00719479  0.01130126]
---------------------
new weights:
[ 0.20034607  0.19979088  0.19990937  0.20008249  0.19987119]
---------------------



PERIOD 532
positions:
[ 25104.00224321  25034.43427162  25049.28141513  25070.97464829
  25044.49821957]
weights:
[ 0.20034607  0.19979088  0.19990937  0.20008249  0.19987119]
rewards:
[ 0.99906338  1.00703723  1.01099908  0.99773448  1.02501064]
returns:
[-0.00093662  0.00703723  0.01099908 -0.00226552  0.02501064]
---------------------
new weights:
[ 0.2003433   0.19978092  0.1999097   0.20007499  0.1998911 ]
---------------------



PERIOD 533
positions:
[ 25422.43587359  25351.07350942  25367.41476815  25388.38902349
  25365.0546978 ]
weights:
[ 0.2003433   0.19978092  0.1999097   0.20007499  0.1998911 ]
rewards:
[ 1.01125     1.00760725  1.01282217  1.00885559  1.02273907]
returns:
[ 0.01125     0.00760725  0.01282217  0.00885559  0.02273907]
---------------------
new weights:
[ 0.2003456   

rewards:
[ 0.99536393  0.98180155  0.99002831  0.99849138  0.99158031]
returns:
[-0.00463607 -0.01819845 -0.00997169 -0.00150862 -0.00841969]
---------------------
new weights:
[ 0.20034918  0.19970359  0.19999574  0.20017245  0.19977903]
---------------------



PERIOD 554
positions:
[ 25522.98759498  25440.7437193   25477.9620947   25500.47319982
  25450.35443527]
weights:
[ 0.20034918  0.19970359  0.19999574  0.20017245  0.19977903]
rewards:
[ 1.00527868  1.01415797  1.01330515  1.0105763   1.0163292 ]
returns:
[ 0.00527868  0.01415797  0.01330515  0.0105763   0.0163292 ]
---------------------
new weights:
[ 0.2003561   0.19969509  0.19998436  0.20018608  0.19977837]
---------------------



PERIOD 555
positions:
[ 25392.56350638  25308.7888101   25345.44963635  25371.0149734
  25319.34357971]
weights:
[ 0.2003561   0.19969509  0.19998436  0.20018608  0.19977837]
rewards:
[ 0.99830116  0.99063189  0.98920113  1.00163748  0.99453728]
returns:
[-0.00169884 -0.00936811 -0.01079887  0.0

[-0.00137447 -0.00461524 -0.0026892  -0.00444194  0.00265562]
---------------------
new weights:
[ 0.20039099  0.19964972  0.19993576  0.2002084   0.19981514]
---------------------



PERIOD 578
positions:
[ 25116.82167825  25023.91139994  25059.76352453  25093.93601218
  25044.64507076]
weights:
[ 0.20039099  0.19964972  0.19993576  0.2002084   0.19981514]
rewards:
[ 0.9946475   0.98627933  0.99858757  0.99631728  0.9902532 ]
returns:
[-0.0053525  -0.01372067 -0.00141243 -0.00368272 -0.0097468 ]
---------------------
new weights:
[ 0.20038381  0.19964091  0.19992783  0.200212    0.19983545]
---------------------



PERIOD 579
positions:
[ 25384.40577981  25290.29639294  25326.64297871  25362.64091296
  25314.94071864]
weights:
[ 0.20038381  0.19964091  0.19992783  0.200212    0.19983545]
rewards:
[ 1.00707257  1.00623621  1.00668638  1.01251066  1.02096929]
returns:
[ 0.00707257  0.00623621  0.00668638  0.01251066  0.02096929]
---------------------
new weights:
[ 0.2004058   0.1996356

positions:
[ 26662.64925964  26555.90804679  26585.86553502  26647.24966705
  26599.94351505]
weights:
[ 0.20039328  0.19959102  0.19981618  0.20027753  0.19992199]
rewards:
[ 1.00336012  1.00141349  0.99948307  0.99876615  1.01310001]
returns:
[ 0.00336012  0.00141349 -0.00051693 -0.00123385  0.01310001]
---------------------
new weights:
[ 0.20039015  0.19958437  0.19983725  0.20026582  0.19992241]
---------------------



PERIOD 603
positions:
[ 26738.28220242  26630.76528179  26664.50738794  26721.69280948
  26675.87137906]
weights:
[ 0.20039015  0.19958437  0.19983725  0.20026582  0.19992241]
rewards:
[ 1.00131043  0.9995295   1.01344712  0.9970091   1.00308791]
returns:
[ 0.00131043 -0.0004705   0.01344712 -0.0029909   0.00308791]
---------------------
new weights:
[ 0.20041367  0.19956229  0.19981079  0.2002715   0.19994175]
---------------------



PERIOD 604
positions:
[ 26757.92360824  26644.25319642  26677.43097298  26738.94264456
  26694.91558845]
weights:
[ 0.20041367  0.1

  26440.43557225]
weights:
[ 0.20042259  0.19956376  0.19991463  0.20015741  0.1999416 ]
rewards:
[ 0.98128456  0.99932783  0.99420897  0.98573584  0.99693046]
returns:
[-0.01871544 -0.00067217 -0.00579103 -0.01426416 -0.00306954]
---------------------
new weights:
[ 0.20041703  0.19954538  0.19990668  0.20016376  0.19996714]
---------------------



PERIOD 627
positions:
[ 26803.62454598  26687.0510313   26735.37072247  26769.75264253
  26743.45611634]
weights:
[ 0.20041703  0.19954538  0.19990668  0.20016376  0.19996714]
rewards:
[ 1.00852478  1.00201787  1.00731193  1.01454014  1.02424709]
returns:
[ 0.00852478  0.00201787  0.00731193  0.01454014  0.02424709]
---------------------
new weights:
[ 0.2004004   0.19956358  0.19990763  0.20015529  0.1999731 ]
---------------------



PERIOD 628
positions:
[ 26518.45799522  26407.72387083  26453.25069034  26486.02379702
  26461.913847  ]
weights:
[ 0.2004004   0.19956358  0.19990763  0.20015529  0.1999731 ]
rewards:
[ 0.98123209  0.998465

positions:
[ 28018.14205386  27902.36763957  27941.89566158  27979.80605499
  27963.47092342]
weights:
[ 0.20040775  0.19957964  0.19986237  0.20013354  0.2000167 ]
rewards:
[ 0.99807481  1.01456177  1.00547379  1.00806181  0.99254059]
returns:
[-0.00192519  0.01456177  0.00547379  0.00806181 -0.00745941]
---------------------
new weights:
[ 0.20038473  0.19955973  0.19984001  0.20021322  0.20000231]
---------------------



PERIOD 651
positions:
[ 28215.41688147  28099.25146306  28138.71625372  28191.26733154
  28161.5688653 ]
weights:
[ 0.20038473  0.19955973  0.19984001  0.20021322  0.20000231]
rewards:
[ 0.99559107  0.99711139  0.99588677  1.04725092  0.99991158]
returns:
[ -4.40892808e-03  -2.88860805e-03  -4.11323494e-03   4.72509164e-02
  -8.84173325e-05]
---------------------
new weights:
[ 0.20039323  0.19955253  0.19982737  0.20020466  0.20002221]
---------------------



PERIOD 652
positions:
[ 28054.69702476  27937.00089232  27975.47764869  28028.29757036
  28002.75493744]


In [ ]:
## Run simulation where constantly rebalance investments
start = time.time()
s = SimulationEnv(initial_wealth, stocks, "data/djia_20150101_20171101/", "2015-01-01", "2017-11-01", NaiveBuyHold, Dummy, True)
s.setup_params(agent_args={})
s.run()

years = 2. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1
end = time.time()

print("Initial wealth: ${}".format(initial_wealth))
print("Final wealth: ${}".format(s.wealth))
print("Annualized return: {}".format(ar))
print("Time: {}s".format(int(end-start)))

In [ ]:
## Run simulation where constantly rebalance investments
start = time.time()
s = SimulationEnv(initial_wealth, stocks, "data/djia_20150101_20171101/", "2015-01-01", "2017-11-01", ConstantRebalancer, Dummy, True)
s.setup_params(agent_args={})
s.run()

years = 2. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1
end = time.time()

print("Initial wealth: ${}".format(initial_wealth))
print("Final wealth: ${}".format(s.wealth))
print("Annualized return: {}".format(ar))
print("Time: {}s".format(int(end-start)))

In [ ]:
## Run simulation where constantly rebalance investments
start = time.time()
s = SimulationEnv(initial_wealth, stocks, "data/djia_20000101_20171101/", "2000-01-01", "2017-11-01", ConstantRebalancer, Dummy, True)
s.setup_params(expert_args={"eta": -0.01})
s.run()

years = 17. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1
end = time.time()

print("Initial wealth: ${}".format(initial_wealth))
print("Final wealth: ${}".format(s.wealth))
print("Annualized return: {}".format(ar))
print("Time: {}s".format(int(end-start)))

In [ ]:
## Run a simulation with Hedge, each expert is a proxy for buying a given stock
start = time.time()

s = SimulationEnv(initial_wealth, stocks, "data/djia_20150101_20171101/", "2015-01-01", "2017-11-01", EG, Dummy, True)
s.setup_params(agent_args = {"eta": -0.01})
s.run(log=True, logpath="logs")

years = 2. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1
end = time.time()

print "Initial wealth: ${}".format(initial_wealth)
print "Final wealth: ${}".format(s.wealth)
print "Annualized return: {}".format(ar)
print "Time: {}s".format(int(end-start))

In [ ]:
## Run a simulation with Hedge, each expert is a proxy for buying a given stock
start = time.time()

s = SimulationEnv(initial_wealth, stocks, "data/djia_20000101_20171101/", "2000-01-01", "2017-11-01", EG, Dummy, True)
s.setup_params(agent_args = {"eta": -0.01})
s.run()

years = 17. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1
end = time.time()

print "Initial wealth: ${}".format(initial_wealth)
print "Final wealth: ${}".format(s.wealth)
print "Annualized return: {}".format(ar)
print "Time: {}s".format(int(end-start))

In [ ]:
## Run a simulation with Hedge, each expert is a proxy for buying a given stock

s = SimulationEnv(initial_wealth, stocks, "data/djia_20150101_20171101/", "2015-01-01", "2017-11-01", EGRecent, Dummy, True)
s.setup_params(agent_args = {"eta": -0.01, "n": 100})
s.run()

years = 2. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1
end = time.time()

print "Initial wealth: ${}".format(initial_wealth)
print "Final wealth: ${}".format(s.wealth)
print "Annualized return: {}".format(ar)
print "Time: {}s".format(int(end-start))

In [ ]:
## Run a simulation with Hedge, each expert is a proxy for buying a given stock

s = SimulationEnv(initial_wealth, stocks, "data/djia_20000101_20171101/", "2000-01-01", "2017-11-01", EGRecent, Dummy, True)
s.setup_params(agent_args = {"eta": -0.01, "n": 750})
s.run()

years = 17. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1
end = time.time()

print "Initial wealth: ${}".format(initial_wealth)
print "Final wealth: ${}".format(s.wealth)
print "Annualized return: {}".format(ar)
print "Time: {}s".format(int(end-start))

In [ ]:
## Run simulation where we just buy and hold all stocks in equal amounts
start = time.time()
s = SimulationEnv(initial_wealth, stocks, "data/djia_20150101_20171101/", "2015-01-01", "2017-11-01", NaiveBuyHold, Dummy, True)
s.setup_params(expert_args={})
s.run()

years = 2. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1
end = time.time()

print "Initial wealth: ${}".format(initial_wealth)
print "Final wealth: ${}".format(s.wealth)
print "Annualized return: {}".format(ar)
print "Time: {}s".format(int(end-start))



In [ ]:
## Run simulation where we just buy and hold all stocks in equal amounts
start = time.time()
s = SimulationEnv(initial_wealth, stocks, "data/djia_20000101_20171101/", "2000-01-01", "2017-11-01", NaiveBuyHold, Dummy, True)
s.setup_params(expert_args={})
s.run()

years = 17. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1
end = time.time()

print "Initial wealth: ${}".format(initial_wealth)
print "Final wealth: ${}".format(s.wealth)
print "Annualized return: {}".format(ar)
print "Time: {}s".format(int(end-start))

In [ ]:
## Run simulation where we each expert only recommends to buy when the price crosses 0.5 standard deviations below the 10-day moving average. 
## Otherwise doesn't do anything
## Sell position when price gets above 0.5 standard deviations below the 10-day MA

start = time.time()

s = SimulationEnv(initial_wealth, stocks, "data/djia_20150101_20171101/", "2015-01-01", "2017-11-01", EG, MeanReversion, True)

s.setup_params(
    agent_args={"eta": -0.01},
    expert_args={"window_size": 10, "threshold": .5}
)

s.run()
end = time.time()
years = 2. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1

print "Initial wealth: ${}".format(initial_wealth)
print "Final wealth: ${}".format(s.wealth)
print "Annualized return: {}".format(ar)
print "Time: {}s".format(int(end-start))

In [ ]:

start = time.time()

s = SimulationEnv(initial_wealth, stocks, "data/djia_20000101_20171101/", "2000-01-01", "2017-11-01", EG, MeanReversion, True)

s.setup_params(
    agent_args={"eta": -0.01},
    expert_args={"window_size": 10, "threshold": .5}
)

s.run()
end = time.time()
years = 17. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1

print "Initial wealth: ${}".format(initial_wealth)
print "Final wealth: ${}".format(s.wealth)
print "Annualized return: {}".format(ar)
print "Time: {}s".format(int(end-start))

In [ ]:

start = time.time()

s = SimulationEnv(initial_wealth, stocks, "data/djia_20000101_20171101/", "2000-01-01", "2017-11-01", EGRecent, MeanReversion, True)

s.setup_params(
    agent_args={"eta": -0.01, "n": 1250},
    expert_args={"window_size": 10, "threshold": .5}
)

s.run()
end = time.time()
years = 17. + 11./12
ar = ((s.wealth)/initial_wealth)**(1/years) - 1

print "Initial wealth: ${}".format(initial_wealth)
print "Final wealth: ${}".format(s.wealth)
print "Annualized return: {}".format(ar)
print "Time: {}s".format(int(end-start))

In [ ]:
start = time.time()
s = SimulationEnv(initial_wealth, stocks, "data/djia_20150101_20171101/", "2015-01-01", "2017-11-01", EG, Momentum, True)

years = 2. + 11./12
s.setup_params(
    agent_args={"eta": -0.01},
    expert_args={"window_size": 10, "threshold": 2.5}
)

s.run()
end = time.time()

ar = ((s.wealth)/initial_wealth)**(1/years) - 1

print "Initial wealth: ${}".format(initial_wealth)
print "Final wealth: ${}".format(s.wealth)
print "Annualized return: {}".format(ar)
print "Time: {}s".format(int(end-start))

In [ ]:
start = time.time()
s = SimulationEnv(initial_wealth, stocks, "data/djia_20000101_20171101/", "2000-01-01", "2017-11-01", EG, Momentum, True)

years = 17. + 11./12
s.setup_params(
    agent_args={"eta": -0.01},
    expert_args={"window_size": 10, "threshold": 2.5}
)

s.run()
end = time.time()

ar = ((s.wealth)/initial_wealth)**(1/years) - 1

print "Initial wealth: ${}".format(initial_wealth)
print "Final wealth: ${}".format(s.wealth)
print "Annualized return: {}".format(ar)
print "Time: {}s".format(int(end-start))

In [ ]:
start = time.time()
s = SimulationEnv(initial_wealth, stocks, "data/djia_20000101_20171101/", "2000-01-01", "2017-11-01", EGRecent, Momentum, True)

years = 17. + 11./12
s.setup_params(
    agent_args={"eta": -0.001, "n": 500},
    expert_args={"window_size": 10, "threshold": 2.5}
)

s.run()
end = time.time()

ar = ((s.wealth)/initial_wealth)**(1/years) - 1

print "Initial wealth: ${}".format(initial_wealth)
print "Final wealth: ${}".format(s.wealth)
print "Annualized return: {}".format(ar)
print "Time: {}s".format(int(end-start))

In [ ]:
pd.__version__